# Pull Docker Hub base image
FROM node:12.18.3-alpine3.12
# Set working directory
WORKDIR /usr/src/backend
# Install app dependencies
COPY package*.json ./
RUN npm install
# Copy app to container
COPY . .
# Run the "dev" script in package.json
CMD ["npm", "start"]